version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: mern_expense_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: expensetracker
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server   
    container_name: mern_expense_backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/expensetracker
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: mern_expense_frontend
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
